# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PH
name: Philipp Henzler
position: Research Scientist 
affiliation: Google
university: University College London

email: philipphenzler14@gmail.com
description: >-
  I am a Research Scientist at [Google](https://ai.google/) working on generative 3D AI.
  I received my PhD from [University College London](http://www.ucl.ac.uk/)
  supervised by [Tobias Ritschel](http://www.homepages.ucl.ac.uk/~ucactri/) and 
  [Niloy J. Mitra](http://www0.cs.ucl.ac.uk/staff/n.mitra/). My PhD thesis received the [Eurographics PhD Thesis award 2024](https://www.eg.org/wp/eurographics-awards-programme/phd-award/).
  
  I received my BSc and MSc from Ulm University in Germany where I am originally from.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://henzler.github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: philipphenzler
github_username: henzler
google_scholar: HVfoUYMAAAAJ
google_analytics: UA-151247604-1
cv: images/Henzler_CV.pdf

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

include:
 - fontawesome

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
